version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build:        
      context: ./back-end/.Net/
      dockerfile: ./ArquitectChallenge.API/Dockerfile
    restart: always
    ports:
      - "7000:80"
    networks: 
      - localdev