version: "3.5"

services:
  nginx:
    image: danillopneto/architect-challenge_nginx
    depends_on:
      - client
      - main-api
    restart: always
    ports:
      - "80:80"

  db:
    image: mysql:8.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: arquitectchallenge
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  main-api:
    image: danillopneto/architect-challenge_main-api
    depends_on:
      - db
    restart: always

  client:
    image: danillopneto/architect-challenge_client
    restart: always
volumes:
  dbdata: