version: '3.5'

services:
  db:
     image: mysql:8.0.0
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: arquitectchallenge
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

  main-api:
    depends_on:
      - db
    build:        
      context: ./back-end/.Net/
      dockerfile: ./ArquitectChallenge.API/Dockerfile
    restart: always
    ports:
      - "5501"

  client:
    build:
        context: ./front-end/angular
        dockerfile: Dockerfile
    ports: 
      - "5000"

  #Proxies requests to internal services
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - client
      - main-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - 8080:80
    restart: always
volumes:
    dbdata: